// Fails unless line coverage of core and domain code is at least 80 %
// (spec M7). Reads coverage/lcov.info from `flutter test --coverage`.
//
//   dart run tool/coverage_gate.dart
import 'dart:io';

/// Not counted, each for a reason:
const _excluded = {
  // Generated by drift_dev make-migrations; exercised by the migration
  // tests, but most of it is schema snapshots that never execute.
  'lib/core/db/app_database.steps.dart',
  // Drift table *declarations*: read by the code generator at build time,
  // never executed in the app.
  'lib/core/db/tables.dart',
  // Android-only WorkManager entry point; runs in a background isolate
  // the test VM can't start (its logic — recurring catch-up and
  // AutoBackup — is tested directly).
  'lib/core/background/background_jobs.dart',
  // Thin wrappers over platform plugins (file dialogs, the on-device
  // database file); tested through fakes.
  'lib/core/files/file_gateway.dart',
  'lib/core/di/database_module.dart',
};

const double _minimum = 80;

void main() {
  final file = File('coverage/lcov.info');
  if (!file.existsSync()) {
    stderr.writeln('Run `flutter test --coverage` first.');
    exit(2);
  }
  final hits = <String, (int, int)>{};
  String? current;
  for (final line in file.readAsLinesSync()) {
    if (line.startsWith('SF:')) {
      current = line.substring(3);
    } else if (line.startsWith('DA:') && current != null) {
      final count = int.parse(line.substring(3).split(',')[1]);
      final (covered, total) = hits[current] ?? (0, 0);
      hits[current] = (covered + (count > 0 ? 1 : 0), total + 1);
    }
  }

  bool counted(String path) =>
      !_excluded.contains(path) &&
      !path.endsWith('.g.dart') &&
      !path.contains('/l10n/gen/');

  var failed = false;
  for (final (name, inScope) in <(String, bool Function(String))>[
    ('core', (p) => p.startsWith('lib/core/')),
    ('domain', (p) => p.contains('/domain/')),
  ]) {
    var covered = 0;
    var total = 0;
    for (final MapEntry(key: path, value: (c, t)) in hits.entries) {
      if (inScope(path) && counted(path)) {
        covered += c;
        total += t;
      }
    }
    final pct = total == 0 ? 100.0 : 100 * covered / total;
    final ok = pct >= _minimum;
    failed |= !ok;
    stdout.writeln(
      '${ok ? 'ok  ' : 'FAIL'} $name: ${pct.toStringAsFixed(1)} % '
      '($covered / $total lines, minimum $_minimum %)',
    );
  }
  exit(failed ? 1 : 0);
}
